# Generated by Django 5.0.1 on 2024-01-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_patientmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
