# Generated by Django 5.0.1 on 2024-04-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_patientmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='status',
            field=models.CharField(blank=True, default='Mark Complete', max_length=50, null=True),
        ),
    ]
